# Day 4: Feature Engineering

In this step, I am creating new useful features from the stock data.  
These features will help the model capture trends and patterns.  

Features to add:
- **Daily Return** → Percentage change in closing price  
- **Moving Averages** → 5-day and 10-day averages of closing prices  
- **Volatility** → Standard deviation of returns (rolling window)  
- **Volume Change** → How trading volume changes day-to-day  

These features will make the dataset richer for analysis and modeling.

In [1]:
# Day 4: Feature Engineering

import pandas as pd

# Load the synthetic stock dataset
stock_data = pd.read_csv("synthetic_stock_data.csv")

# Create new features
stock_data["daily_return"] = stock_data["close"].pct_change().fillna(0)
stock_data["ma_5"] = stock_data["close"].rolling(window=5).mean().fillna(method="bfill")
stock_data["ma_10"] = stock_data["close"].rolling(window=10).mean().fillna(method="bfill")
stock_data["volatility_5"] = stock_data["daily_return"].rolling(window=5).std().fillna(0)
stock_data["volume_change"] = stock_data["volume"].pct_change().fillna(0)

# Save updated dataset
stock_data.to_csv("synthetic_stock_data_with_features.csv", index=False)

print("Feature engineering completed. New dataset saved as 'synthetic_stock_data_with_features.csv'")
stock_data.head()

Feature engineering completed. New dataset saved as 'synthetic_stock_data_with_features.csv'

C:\Users\pc\AppData\Local\Temp\ipykernel_7608\2135626136.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  stock_data["ma_5"] = stock_data["close"].rolling(window=5).mean().fillna(method="bfill")
C:\Users\pc\AppData\Local\Temp\ipykernel_7608\2135626136.py:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  stock_data["ma_10"] = stock_data["close"].rolling(window=10).mean().fillna(method="bfill")

,date,open,high,low,close,volume,daily_return,ma_5,ma_10,volatility_5,volume_change
0,2023-01-02,100.68,101.05,99.23,99.70,1886,0.000000,101.078,102.395,0.000000,0.000000
1,2023-01-03,100.64,101.10,99.80,100.06,1427,0.003611,101.078,102.395,0.000000,-0.243372
2,2023-01-04,101.55,101.98,100.96,101.01,2328,0.009494,101.078,102.395,0.000000,0.631395
3,2023-01-05,103.06,103.73,102.32,102.55,2895,0.015246,101.078,102.395,0.000000,0.243557
4,2023-01-06,101.61,102.28,101.39,102.07,2994,-0.004681,101.078,102.395,0.007834,0.034197